CREATE TABLE SPEECH (
    ID UUID PRIMARY KEY,
    AUTHOR VARCHAR(255) NOT NULL,
    SPEECH_DATE DATE NOT NULL,
    CONTENT TEXT NOT NULL
);

CREATE TABLE KEYWORDS (
    ID UUID PRIMARY KEY,
    SPEECH_ID UUID NOT NULL,
    KEYWORD VARCHAR(255) NOT NULL,
    CONSTRAINT fk_speech FOREIGN KEY (SPEECH_ID) REFERENCES SPEECH(ID) ON DELETE CASCADE
);

CREATE INDEX idx_keyword_keyword ON KEYWORDS(KEYWORD);
CREATE INDEX idx_keyword_speech_id ON KEYWORDS(SPEECH_ID);